### ISSUE TITLE
KS1 new firmware issue

### ISSUE THREAD

**Issue by faradayads** [incidrthreat/iceriver_oc#10]
I have no problem with the KS1 ks1OCupdate overclocking firmware. I switched to the newly updated KS1 firmware ks1update25.bgz, which can only run 600g of computing power. Even if you restore the factory Settings and use ks1OCupdate, you can only run 600g.

**Comment by faradayads** [comment]
what i can do for it?

**Comment by faradayads** [comment]
@incidrthreat

**Comment by incidrthreat** [comment]
Unfortunately some ASICs are hit or miss on the OC due to "silicon lottery".   A good rule of thumb is, if your ASIC is under performing after an update then reload the iceriver official FW.  We recommending using the webgui for any updates instead of using the Eclipse IDE. But if the Eclipse IDE is the only access a user has, please place any update FW files (OC or Iceriver official) in the `/var/volatile/tmp/bg/uploads` directory and restart.

Join us on the Kaspa Discord if you have any further questions or want to interact with this amazing community. https://discord.com/invite/kS3SK5F36R

**Comment by faradayads** [comment]
Yesterday I used ks1OCupdate no problem, why changed ks1update25 before the failure @incidrthreat

**Comment by faradayads** [comment]
How do I restore my miner to a state without using ks1update25.bgz to use ks1OCupdate.bgz
