### ISSUE TITLE
KS0 overclock issues on first batch (Jun 2023)

### ISSUE THREAD

**Issue by freideee** [incidrthreat/iceriver_oc#12]
I have 4x KS0, 2 from the very first batch, and 2 from second batch.

Both second batch miners are running 160g firmware happily, however both first batch KS0 are encountering issue on the firmware.

I tried 160g / 150g firmware on both problematic miners, both are not hashing. I connected to Herominers and were able to see they are connected, but retargetted to lower difficulties (same on kaspa-pool.org) but did not submit any share at all.

I then tried 140g firmware on both, they are getting 111 to 112g constantly. 

I again tried 120g firmware, and they were working as expected. 119-121g.

I am wondering if anyone else have first batch KS0 having the same issue, or i am so unlucky that both first batch KS0 cannot go beyond 120g.

Thanks.

**Comment by freideee** [comment]
tried update via Eclipse IDE as well, still not working. I guess the only way to have it mining now is use 120g firmware.

**Comment by incidrthreat** [comment]
Unfortunately the first batch seems to be hit or miss on the OC due to "silicon lottery".  We recommending using the webgui for any updates instead of using the Eclipse IDE.  But if the Eclipse IDE is the only access a user has, please place any update FW files (OC or Iceriver official) in the `/var/volatile/tmp/bg/uploads` directory and restart.

Join us on the Kaspa Discord if you have any further questions or want to interact with this amazing community. https://discord.com/invite/kS3SK5F36R
