### ISSUE TITLE
KS0 No update changes hash rate...

### ISSUE THREAD

**Issue by speedyfoxai** [incidrthreat/iceriver_oc#24]
I have tried all the original files and the new 120~`160 files, always reboots and mines at 100gh. 
I just went to try the Eclipse method but the "miner.bgz" file has been removed... Ugh...

I just got my 2nd KS0 and same thing happens... I flash with up to day firmware and reboot, works fine. I flash with any other and reboot and 100gh... 

Please put the miner.bgz file back up so I can try that method... 

Thanks.

**Comment by JustLook12** [comment]
What are the exact steps you do to do oc?
Steps are: 
1. Update machine to ice river firmware (note you might want to download it and store it locally).
2. Restart machine
3. Update with oc modded  (see note you might want to store file locally)
4. Restart (by power of or webgui restart)
5. Wait till hashes. That should do it. 

Here is a link for the eclips method miner.bgz file : [https://we.tl/t-S84ObvArji](https://we.tl/t-S84ObvArji?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)
Use at own risk ofcourse (i am not of the team). 
note: in 7 days link will expire (so download and store locally)

steps eclipse: (copy from readme.dm)
Before proceeding, please read the [disclaimer](../DISCLAIMER.md).

1. Once inside Eclipse IDE and successfully connected, head over to File System tab below.
2. Navigate to `/var/update` and delete `miner.bgz`. 
3. Upload by dragging/dropping the modified [miner.bgz](./files/miner.bgz) provided into the `/var/update` folder.  
    - SHA256: `dbe03cc291e2f9047ff8765f4638de3933b698357f953ec3d6c9e85b567e0b78  miner.bgz`
4. Once the transfer is complete, reboot via SSH, Webgui, or the good 'ol fashion unplug/replug method.
5. After about 2-5 minutes the webgui should be accessible again.  Miner hashrate will range bw 140-160 GH/s depending on silicon lottery.

**Comment by speedyfoxai** [comment]
Done over and over. I got 3 new ones today and they all do the same. 
Out of the box.
1. Connect new psu boot up.
2. Flash updated IR firmware, reboot.
3. Once back up, flash with (ANY) OC firmware.
4. Reboot.
5. 100gh... 

I tried the Eclipse method and it doesn't boot when I put the miner file in the directory. 
edit: It does still let me connect through Eclipse and restore the original miner file and then it boots. 
Yes, I waited about 15 min... :)

Have you been using the IR firmware from 9-23? That is the one I am using. 

I have tried holding the button and factory resetting it and doing steps over and over. None of the 4 I have will take the OC, they do boot and run, but ~100gh only. 
I even tried your original update file... Nothing... 

Let me know if I can be of more help... 

Fyi... I am a software developer so none of these steps are new to me...

**Comment by JustLook12** [comment]
> Done over and over. I got 3 new ones today and they all do the same. Out of the box.
> 
> 1. Connect new psu boot up.
> 2. Flash updated IR firmware, reboot.
> 3. Once back up, flash with (ANY) OC firmware.
> 4. Reboot.
> 5. 100gh...
> 
Well that sounds correct way to do things, i can only say then you are most unlucky. 

> I tried the Eclipse method and it doesn't boot when I put the miner file in the directory. edit: It does still let me connect through Eclipse and restore the original miner file and then it boots. Yes, I waited about 15 min... :)

Usually when you have it, that it does not boot (while applying an OC FW)  the Firmware on machine before update was original shipped firmware and not the recent update firmware of Ice river. 
My expirience i could not do straight away the OC mod i needed to update Firmware first with Iceriver (16/9 release) (also with Eclips method). 
Maybe re-check it again on only 1 machine? 

> 
> Have you been using the IR firmware from 9-23? That is the one I am using.

Its not 9-23 its 16-9-23 which i downloaded locally (online and what i have here locally are still the same) 

> 
> I have tried holding the button and factory resetting it and doing steps over and over. None of the 4 I have will take the OC, they do boot and run, but ~100gh only. I even tried your original update file... Nothing...

Resetting (either by button or webgui) reverts firmware to original shipped, so it whipes the Firmware of Iceriver. I had it once i resetted machine thought i already updated FW to Latest IR so skipped the step, machine ended up not booting only through Eclips i could reach it. I re-resetted and first updated with IR FW. .... Then OC file - it worked. 
> 
> Let me know if I can be of more help...
>
Well to be honest as you mentioned above it sounds like correct way to update. 
Maybe try this, do a factory reset, update with FW IR , then OC mod. (ofcourse with reboots in between) check it for 1 miner if it works. 

> 
> Fyi... I am a software developer so none of these steps are new to me...

It is frustrating if something does not work as it should, we make mistakes it might be especially if you did things 10x already. I can only say i have 4 ks0 (here now) i had 5 machines and all 5 machines i was able to OC to 160 Gh/s. Latest miners i received believe last monday so they are last batch.... 
I cannot believe you are so unlucky all your machines are well unlockable. 

I have no other wisdom to share since this is my expirience on how to update. Maybe review for 1 miner, don't fight with 4 just one. 
Keep us informed if succesfull

**Comment by speedyfoxai** [comment]
@JustLook12 Hey... Still trying to get it to work. However I did find one strange thing. Sometimes I can't access the web gui... It says connection refused. BUT... If I go to another browser then I can connect and it allows the original browser to connect. For example. I use Brave Browser. If it wont connect there is nothing I can do to get it to work even if the other 3 I have are working fine. If I go to firefox it opens and I can log in, and then brave works after that... So weird... 

So still with my original issue, I tried flashing from Linux Brave Browser and it didn't work. So I am going to try firefox or ie next... Maybe something strange with browsers... I am out of ideas... lol

**Comment by JustLook12** [comment]
>Hey... Still trying to get it to work. However I did find one strange thing. Sometimes I can't access the web gui... It says >connection refused. BUT... If I go to another browser then I can connect and it allows the original browser to connect. For >example. I use Brave Browser.

Strange to be honest, could it be that (i am assuming you saved passwords in browser that brave knows an incorrect password while firefox browser does not ?

> If it wont connect there is nothing I can do to get it to work even if the other 3 I have are working fine. 

You always have the eclips method and ofcourse factory reset.

>So still with my original issue, I tried flashing from Linux Brave Browser and it didn't work. So I am going to try firefox or ie >next... Maybe something strange with browsers... I am out of ideas... lol

I thought you wanted to try through eclipse method.

**Comment by speedyfoxai** [comment]
I tried the eclipse method as well. Many times. lol

**Comment by speedyfoxai** [comment]
Any updates on this? I have 4 KS0s and all only doing ~100gh... I would like more. :)

**Comment by speedyfoxai** [comment]
Holy crap. It's resolved. I r-clicked to dl the files. Turns out it doesn't download correctly, have to use the github download button. 335kb with r-click dl, and actual size with download is 11,402kb!!!
