### ISSUE TITLE
Excessive Rejected Shares

### ISSUE THREAD

**Issue by Sudboyz** [incidrthreat/iceriver_oc#26]
I have tried all OC's on my 3 KS0's. Every time I get greatly improved hashrates, but 30%+ rejected shares as shown on the pool side AND in the web gui. Restoring the IceRiver firmware takes me down to sub 1%. I have let them run on different pools for 3-5 days each but no improvement in the rejected shares.

**Comment by JustLook12** [comment]
I cannot comment on rejected shares as i do solo and at own node. I have approx zero rejected shares, but ofcourse it does not count since i run solo. My 4 machines are all at 160 gh/s but by temperatures are max 52 c. Now due to autumn temperatures are below 50 c. Is cooling maybe a solutions since 30% is a lot

**Comment by Spindler360** [comment]
> I have tried all OC's on my 3 KS0's. Every time I get greatly improved hashrates, but 30%+ rejected shares as shown on the pool side AND in the web gui. Restoring the IceRiver firmware takes me down to sub 1%. I have let them run on different pools for 3-5 days each but no improvement in the rejected shares.

30% I find very violent. With me it is about 4% after the update. Before it was <1%. But I think that is acceptable.
Did you update to the described Iceriver firmware (ICERIVER-KAS-KS0-20230916) before the OC update? 
If so, try the next small OC update. Depending on the batch and Silicon Lottery it can have different effects.

> I cannot comment on rejected shares as i do solo and at own node. I have approx zero rejected shares, but ofcourse it does not count since i run solo. My 4 machines are all at 160 gh/s but by temperatures are max 52 c. Now due to autumn temperatures are below 50 c. Is cooling maybe a solutions since 30% is a lot

To reduce the temperature, please make sure your miner is well ventilated. Place it a few centimeters/inches higher than the shelf or table; install a 120mm fan on the miner and set the two Iceriver fans to Auto mode or 100%.

**Comment by Sudboyz** [comment]
My temps are great, running with a 5v noctua fan on each in a 70 F ambient temp area. I reinstalled the iceriver firmware, and reattempted with the 160gh OC and now they are 1%-3% stale/rejected.

**Comment by tlopez1951** [comment]
I too have been seeing this with my miners however, doing a factory reset, upgrading the firmware, and re-applying the overclocks does help to lower the rejects reported from 30% down to roughly 20%. This is still way too high to be acceptable but I am wondering if these numbers may not be entirely correct and rather a software glitch within the iceriver interface. I say this because when I check on the mining web site I don't see any invalid shares reported instead it shows valid vs. stale shares which is typically under 3% in a given 24hr period.
