### ISSUE TITLE
Stock FW

### ISSUE THREAD

**Issue by chad5150** [incidrthreat/iceriver_oc#31]
Any chance you have the stock files? If i factory restore from an OC the save button becomes inactive. I can press it until the cows come home but it does not bring up the conformation of success popup. Im not able to open the ELF files or the bgz files because i havent been able to get petalinux to work correctly with wsl. I may be off base but the only thing i can think of is in the bg.sh file if you follow the progression towards the end it makes a call  to the appweb file. If this is changed in any way from the iceriver beta firmware update which the OC's are based on then it may be this file that is borked. Just a theory.

**Comment by incidrthreat** [comment]
Petalinux will continue to have issues in WSL bc the architecture on the Iceriver hosts are ARM based--Your windows machine is not ARM based.  You'd have a better chance to mimic the env on a Raspberry Pi.

Having said that, there is no need to edit the host system in order to get the OC to work.  We have provided everything necessary to update/flash via the webgui.  Stock firmware can be found here: https://www.iceriver.io/firmware-download/  Hopefully this helps.

**Comment by chad5150** [comment]
Thanks for quick response. Ill give a rasberry pi a try for the fun of it all. Thanks for the link.
